Implement a TestClient class to test routes more efficiently
sparckles/Robyn pull request #567
Opened 2023-07-27 20:45 UTC by ElyasMag

**Description**

This PR fixes #

2023-08-01 21:24 UTC, sansyrox commented on robyn/testing.py
> +	return r
We can move this function inside the class only 😄

2023-08-01 21:27 UTC, sansyrox commented
Hey @ElyasMag 👋 

Thanks for the PR 😄 I have had an initial look. I will have a deeper look as you make more progress 😄 

Do let me know if you have any questions from my end!

2023-08-02 01:30 UTC, ElyasMag commented
> Hey @ElyasMag 👋
> 
> Thanks for the PR 😄 I have had an initial look. I will have a deeper look as you make more progress 😄
> 
> Do let me know if you have any questions from my end!

Hello! I'm new here. I'd appreciate any help I can get. I have one main question: If you look at my testing.py, you'll see that I'm passing None to the route handler. I tried to create a Request object to pass into it, but I get an error saying "class has no constructor." If you have any advice to offer, it would be much appreciated.

2023-08-02 21:42 UTC, ElyasMag commented
> > Hey @ElyasMag 👋
> > Thanks for the PR 😄 I have had an initial look. I will have a deeper look as you make more progress 😄
> > Do let me know if you have any questions from my end!
> 
> Hello! I'm new here. I'd appreciate any help I can get. I have one main question: If you look at my testing.py, you'll see that I'm passing None to the route handler. I tried to create a Request object to pass into it, but I get an error saying "class has no constructor." If you have any advice to offer, it would be much appreciated.

@sansyrox Mentioning in case you didn't get a notification.

2023-08-02 22:05 UTC, sansyrox commented
Hey @ElyasMag 👋 

>  I tried to create a Request object to pass into it, but I get an error saying "class has no constructor." If you have any advice to offer, it would be much appreciated.


There are two reasons for this 

One is that you need to inspect the kind of params the handler is expecting 
And second, where are you importing the request class from?

2023-08-07 03:23 UTC, ElyasMag commented
@sansyrox Sorry, I can't seem to figure it out,
1. As far as I can tell, the only parameter passed into the handler - that is, the function written by the developer of a server using Robyn - is the Request object.
2. I'm importing the Request class from the robyn library, which I believe comes from src/types/request.rs & robyn/robyn.pyi

I thought I would have to create a class implementing the Request class, but Request is not an acceptable base type. Creating my own class with the same fields as the Request class would probably work, but doesn't sound like a reasonable solution. I can't figure out any other method of passing a Request object to the handler.
Once again, advice would be greatly appreciated.

2023-08-08 17:31 UTC, parth-gr commented on robyn/testing.py
> +from robyn import Request, Response
@ElyasMag try this

from robyn.robyn import Router

router = Router(...)
print router.getRoute()

2023-08-15 17:04 UTC, parth-gr commented on robyn/testing.py
> +
only one line

2023-08-17 07:05 UTC, parth-gr commented
Update the description of the PR and also attach the issue,

Undraft the PR so you can get a round of review from the maintainers

2023-08-17 07:25 UTC, sansyrox commented
Hey @ElyasMag 👋 

> @sansyrox Sorry, I can't seem to figure it out, As far as I can tell, the only parameter passed into the handler - that is, the function written by the developer of a server using Robyn - is the Request object.
I'm importing the Request class from the robyn library, which I believe comes from src/types/request.rs & robyn/robyn.pyi
I thought I would have to create a class implementing the Request class, but Request is not an acceptable base type. Creating my own class with the same fields as the Request class would probably work, but doesn't sound like a reasonable solution. I can't figure out any other method of passing a Request object to the handler.
Once again, advice would be greatly appreciated.

Apologies, I missed this message :( .

Thanks @parth-gr for the help 💖 

Do you still have any queries??

2023-08-17 09:10 UTC, ElyasMag commented
> Hey @ElyasMag 👋
> 
> > @sansyrox Sorry, I can't seem to figure it out, As far as I can tell, the only parameter passed into the handler - that is, the function written by the developer of a server using Robyn - is the Request object.
> > I'm importing the Request class from the robyn library, which I believe comes from src/types/request.rs & robyn/robyn.pyi
> > I thought I would have to create a class implementing the Request class, but Request is not an acceptable base type. Creating my own class with the same fields as the Request class would probably work, but doesn't sound like a reasonable solution. I can't figure out any other method of passing a Request object to the handler.
> > Once again, advice would be greatly appreciated.
> 
> Apologies, I missed this message :( .
> 
> Thanks @parth-gr for the help 💖
> 
> Do you still have any queries??
> 
> And for the future, if I don't reply to a query within 48 hours, feel free to reach out to me on Discord 😄

Hello @sansyrox!
I'll keep that in note for the future. The CodeDay Labs program is ending soon but I'd definitely like to continue working on this after.
How is my approach looking? I noticed that in the description of the issue, the functions' arguments and return values matched those of the request library instead of those of the robyn library, so I tried to implement them similarly.

2023-08-17 17:51 UTC, parth-gr commented on testclient_example/testclient.py
> +from robyn_server import app
myapp

2023-08-17 18:04 UTC, parth-gr commented on robyn/testing.py
> +        #run the handler function
leave a line

2023-08-17 18:05 UTC, parth-gr commented on robyn/testing.py
> +        r = Response()
attached the issue why not used the robyn response and also the reason as a todo

2023-08-17 18:06 UTC, parth-gr commented on robyn/testing.py
> +            body, header = encode_multipart_formdata(files)
can we call a separate function for this, single function not looks good

2023-08-17 18:06 UTC, parth-gr commented on robyn/testing.py
> +        r.status_code = response.status_code
this should be a separate function

2023-08-17 18:07 UTC, parth-gr requested changes

2023-08-17 18:07 UTC, parth-gr commented on testclient_example/testclient.py
> +from robyn.testing import TestClient
We need to add a document step on the glow how to run this from the end user perspective

2023-08-17 18:08 UTC, parth-gr commented on robyn/testing.py
> +# until we figure out a better method, I will be copying the classes over
explain the issue OF CONSTRUCTOR

Why we need to do this provide URL links,

2023-08-17 18:10 UTC, parth-gr commented on robyn/testing.py
> +        req.headers["host"] = "localhost"
have a separate function for headers,
And do it for every param

2023-08-17 18:12 UTC, parth-gr commented on robyn/testing.py
> +            if type(data) == bytes:
I don't think we need to do for single type there might a function in python that would be handelling it

2023-08-22 07:31 UTC, IdoKendo requested changes
Hey @ElyasMag 👋 
Awesome work! I've left a few comments, let me know if anything's unclear 😃

2023-08-24 19:27 UTC, IdoKendo commented on testclient_example/testclient.py
> +test_index()
When you run pytest it discovers functions that begin or end with test and runs them.

2023-08-28 06:59 UTC, ElyasMag commented
@sansyrox
Hey! I have a couple of questions to ask, if you don't mind answering them!
- What is the Identity field of the Request class?
- Do redirects need to be handled by the testing client? I'm looking at the Digest authentication and it involves some back-and-forth which the HttpDigestAuth class attaches hooks to the request for. This involves a lot of extra functions so if that's the case, then I might need to revisit my approach for the test requests entirely.

2023-08-28 12:36 UTC, parth-gr commented on robyn/testing.py
> +    def add_cookies(self, req, cookies):
leave a line between functons

2023-08-29 10:38 UTC, IdoKendo commented
Hey @ElyasMag 👋 
I see that there are quite a few formatting/linting issues - We have pre-commit set up in the repo with `black` and `ruff` to avoid these and fix them at the commit step.
If you follow the [local development guide](https://github.com/sparckles/robyn#%EF%B8%8F-to-develop-locally) you can see how to set it up.
You can run `pre-commit run --all-files` after you set it up to run it on all files that you've previously committed.
Feel free to reach out if you're having issues!

2024-03-17 23:21 UTC, closed without merging