Replace `url` parameter in the `app.start`
sparckles/Robyn pull request #614
Opened 2023-09-25 23:47 UTC by carlosm27

**Description**
Replacing `url` parameter for `host` parameter in the `start` method.
This PR fixes #613

2023-09-26 10:22 UTC, sansyrox commented
Hey @carlosm27 👋 No changes are showing up in the diff. Is this expected?? 😅

2023-09-27 19:16 UTC, sansyrox reviewed
This looks great @carlosm27 😄 Good job! Can you please add some documentation regarding it too

2023-09-28 01:44 UTC, carlosm27 commented
> This looks great @carlosm27 😄 Good job! Can you please add some documentation regarding it too

Yes, no problem

2023-09-29 19:09 UTC, sansyrox commented
Hey @carlosm27 👋 

Can you please update the docs in the new_docs/documentation folder as well??

2023-09-29 23:46 UTC, carlosm27 commented
> Hey @carlosm27 👋
> 
> Can you please update the docs in the new_docs/documentation folder as well??

Absolutely

2023-10-01 00:23 UTC, carlosm27 commented
Hey @sansyrox. Do I update only the `getting_started` page or all the pages where the `app.start()` appears?

2023-10-01 19:22 UTC, sansyrox commented
Hey @carlosm27 👋 

> Hey @sansyrox. Do I update only the getting_started page or all the pages where the app.start() appears?

I think a simple find and replace would work 🤔

2023-10-02 21:25 UTC, sansyrox commented on robyn/__init__.py
> +    def start(self, host: str = "127.0.0.1", port: int = 8080):
```suggestion
    def start(self, host: str = "127.0.0.1", port: int = 8080, *, url: str="127.0.0.1"):
```

2023-10-02 21:25 UTC, sansyrox commented on robyn/__init__.py
> +        host = os.getenv("ROBYN_URL", host)
```suggestion
        host = os.getenv("ROBYN_URL", host) or os.getenv("ROBYN_URL", url) 
```

2023-10-02 21:26 UTC, sansyrox commented on robyn/__init__.py
> +        host = os.getenv("ROBYN_URL", host)
Also, I think if we should replace this environment variable with `ROBYN_HOST`

2023-10-02 21:27 UTC, sansyrox submitted a review, later dismissed
Hey @carlosm27 :wave: 

Thank you for your PR :smile: I have suggested some changes as I plan to gradually break compatibility. We will completely remove the URL after 2-3 major releases.

2023-10-03 13:55 UTC, carlosm27 commented
> Hey @carlosm27 👋
> 
> Thank you for your PR 😄 I have suggested some changes as I plan to gradually break compatibility. We will completely remove the URL after 2-3 major releases.

Hey @sansyrox thank you for taking a time and reviewing my PR. I appreciate it.

2023-10-06 19:12 UTC, sansyrox commented
Hey @carlosm27 👋 

Windows tests are failing for some reason. Can you please have a look?

2023-10-07 00:48 UTC, carlosm27 commented
> Hey @carlosm27 👋
> 
> Windows tests are failing for some reason. Can you please have a look?

Hey @carlosm27. Yes, no problem.

2023-10-07 15:24 UTC, IdoKendo requested changes
Hey @carlosm27 👋 
Great work! I am not sure though that keeping support for `url` is needed - if we want to retain backwards compatibility for a bit, then I think the approach should be a bit different, refer to my comments. Also, we'll need to add warning logs to notify about deprecation.

Anyway, from previous PRs in the repo, I think breaking changes are acceptable before v1, so not sure it's even worth the trouble. @sansyrox WDYT?

2023-10-07 15:24 UTC, IdoKendo commented on robyn/__init__.py
> +        self, host: str = "127.0.0.1", port: int = 8080, *, url: str = "127.0.0.1"
Why do we still need url as a keyword-only argument?

2023-10-07 15:24 UTC, IdoKendo commented on robyn/__init__.py
> +        host = os.getenv("ROBYN_HOST", host) or os.getenv("ROBYN_URL", url)
I think an `or` condition here is wrong. If someone passes `url="0.0.0.0"` it will still be `127.0.0.1` due to `host`'s default value.

2023-10-09 20:11 UTC, sansyrox commented
Hey @IdoKendo 👋 

> Anyway, from previous PRs in the repo, I think breaking changes are acceptable before v1, so not sure it's even worth the trouble. @sansyrox WDYT?

I suppose you are right here. And url/host are positional params too. Will not be a super big breaking change.

2023-10-09 20:18 UTC, sansyrox commented
Hey @carlosm27 👋 

All good now. Can you please update the docs too? We have references to `ROBYN_URL` in a lot of places. Can you replace it with `ROBYN_HOST`?

2023-10-09 20:19 UTC, carlosm27 commented
> Hey @carlosm27 👋
> 
> All good now. Can you please update the docs too? We have references to `ROBYN_URL` in a lot of places. Can you replace them with `ROBYN_HOST`?

Hey @sansyrox. Yes, absolutely.

2023-10-09 21:01 UTC, IdoKendo requested changes

2023-10-09 21:01 UTC, IdoKendo commented on integration_tests/test_env_populator.py
> +    HOST = os.environ["ROBYN_URL"] or os.environ["ROBYN_HOST"]
Don't forget to remove this or condition as well

2023-10-10 21:43 UTC, sansyrox approved these changes
LGTM 🔥 Great work @carlosm27

2023-10-10 21:44 UTC, merged

2024-04-09 18:54 UTC, FattyMango commented
This should also be replaced in robyn --create

this is what it generates using `robyn --create`

```python
if __name__ == "__main__":
    app.start(url="0.0.0.0", port=8080)
```
it should be changed to 

```python
if __name__ == "__main__":
    app.start(url="0.0.0.0", port=8080)

# OR
    
if __name__ == "__main__":
    app.start(port=8080)
```