feat: openapi response schema
sparckles/Robyn pull request #932
Opened 2024-08-19 05:14 UTC by VishnuSanal

## Description

This PR fixes #930

## Summary

This PR adds response schema to openapi docs

## PR Checklist

Please ensure that:

- [x] The PR contains a descriptive title
- [x] The PR contains a descriptive summary of the changes
- [x] You build and test your changes before submitting a PR.
- [ ] You have added relevant documentation
- [ ] You have added relevant tests. We prefer integration tests wherever possible

## Pre-Commit Instructions:

- [x] Ensure that you have run the [pre-commit hooks](https://github.com/sansyrox/robyn#%EF%B8%8F-to-develop-locally) on your PR.

2024-08-19 14:39 UTC, VishnuSanal commented
The schema will be defaulted to "any" for now; until typing is implemented. @sansyrox PTAL. I am not sure whether this was the expectation -- CMIIW.

2024-08-19 18:42 UTC, sansyrox commented on robyn/openapi.py
> +            "responses": {"200": {"description": "Successful Response", "content": {"application/json": {"schema": {}}}}},
@VishnuSanal ,
> Ensure that you have run the [pre-commit hooks](https://github.com/sansyrox/robyn#%EF%B8%8F-to-develop-locally) on your PR.

These were not run here

2024-08-19 18:44 UTC, sansyrox commented on robyn/openapi.py
> +            "responses": {"200": {"description": "Successful Response", "content": {"application/json": {"schema": {}}}}},
@VishnuSanal , we have typing at the moment. e.g. regular response vs json response. We need to distinguish between that on return type.

2024-08-19 18:50 UTC, sansyrox commented
<img width="1597" alt="Screenshot 2024-08-19 at 19 48 57" src="https://github.com/user-attachments/assets/6e97601c-80cb-4ae1-bd49-74d8889524ef">


@VishnuSanal , there is also an issue in rendering of the docstrings in the application.

The above is an expected response.


But what happens is the one below

<img width="1582" alt="Screenshot 2024-08-19 at 19 50 13" src="https://github.com/user-attachments/assets/0a78d165-056a-40a9-a590-f2908548bad6">

2024-08-19 18:50 UTC, sansyrox commented
@VishnuSanal , could you fix it?

2024-08-20 03:07 UTC, VishnuSanal commented
> @VishnuSanal , there is also an issue in rendering of the docstrings in the application.

what is the issue? the location where the description is shown? fastapi might be using a slightly different version of swagger; that must be the reason. should investigate. is this a major breaking feature? isn't it just about the aesthetics?

2024-08-20 09:05 UTC, sansyrox commented
> what is the issue? the location where the description is shown? fastapi might be using a slightly different version of swagger; that must be the reason. should investigate. is this a major breaking feature? isn't it just about the aesthetics?

The issue is that Robyn's docstrings are not legible. We are appending them to the wrong location! This is may be due to a different version of swagger but feels more like wrong openapi.json generation.

Hence, a blocking issue, which needs to be fixed before merging

2024-08-20 09:05 UTC, sansyrox requested changes
Need to fix the openapi docs generation

2024-08-20 09:09 UTC, sansyrox commented
The docstrings are being appended only to the `summary`. They should also be added to the `description` field.

2024-08-20 14:21 UTC, VishnuSanal commented
@sansyrox done, PTAL. although unrelated, I have also removed openapi integration from future roadmap in the docs -- hope this is okay & need not create a new PR.

2024-08-20 15:50 UTC, VishnuSanal commented
Todo: fix CI

2024-08-21 10:05 UTC, merged